services:
  backend:
    build: ./backend/
    volumes:
      - ./backend:/backend
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
volumes:
  bundle:
  postgresql_data:
