inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.3
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'db/schema.rb'

# NOTE: class/module のコメントは書かなくてよい
Style/Documentation:
  Enabled: false

# NOTE: ネストさせるとModelの挙動が変わるので `compact`
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/**/*'

# NOTE: config だけ行の文字数制限をしない
Layout/LineLength:
  Exclude:
    - 'config/**/*'

# NOTE: RSpecの `context` で when や with などを使うことを強制しない
RSpec/ContextWording:
  Enabled: false

# NOTE: テストの最大確認数を「5」にする
RSpec/MultipleExpectations:
  Max: 5
